"""fix bd

Revision ID: 8d42c1b9a480
Revises: 744551650ab2
Create Date: 2024-12-08 02:14:20.326643

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8d42c1b9a480'
down_revision = '744551650ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
